replicaCount: 1

image:
  repository: ghcr.io/movinglake/pg_webhook
  pullPolicy: IfNotPresent
  tag: "0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

postgres:
  # If the secret is enabled, get the postgres URL from the secret
  # value given in `postgres.secret.name` and `postgres.secret.key`
  secret:
    enabled: false
    name: ""
    key: ""
  url: "postgres://postgres:postgres@localhost:5432/postgres"
  replicationSlot:
    name: ""

persistence:
  enabled: false
  size: 1Gi
  storageClassName: "gp2"
  path: /data

webhook:
  url: "http://localhost:8080"

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
